'use client';

import { useState } from 'react';
import { DashboardHeader } from '@/components/dashboard-header';
import { useUser, useDoc, useMemoFirebase, useFirestore } from '@/firebase';
import { doc } from 'firebase/firestore';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { BookMarked, Wand2, Lightbulb } from 'lucide-react';
import { generateStudyGuide } from '@/ai/flows/study-guide-generator';
import { Label } from '@/components/ui/label';

export default function AiStudyGuidePage() {
    const { user } = useUser();
    const firestore = useFirestore();
    const userProfileRef = useMemoFirebase(() => {
        if (!firestore || !user?.uid) return null;
        return doc(firestore, 'users', user.uid);
    }, [firestore, user?.uid]);
    const { data: userProfile } = useDoc(userProfileRef);

    const [topic, setTopic] = useState('');
    const [subject, setSubject] = useState('');
    const [guide, setGuide] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!topic.trim() || !subject.trim()) return;

        setIsLoading(true);
        setGuide('');
        setError(null);

        try {
            const result = await generateStudyGuide({ topic, subject });
            setGuide(result.guide);
        } catch (err) {
            console.error(err);
            setError('An error occurred while generating the study guide. Please try again.');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="flex flex-col min-h-screen bg-muted/40">
            <DashboardHeader userName={userProfile?.name} userRole="student" />
            <main className="flex-1">
                <div className="container mx-auto p-4 md:p-8">
                    <div className="flex items-center gap-4 mb-6">
                        <BookMarked className="h-8 w-8 text-primary" />
                        <h1 className="text-3xl font-bold">AI Study Guide Generator</h1>
                    </div>

                    <Card className="max-w-3xl mx-auto">
                        <CardHeader>
                            <CardTitle>Create a Study Guide</CardTitle>
                            <CardDescription>Enter a topic and subject to get a custom study guide generated by AI, including key concepts and practice questions.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <form onSubmit={handleSubmit} className="space-y-4">
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    <div className="space-y-2">
                                        <Label htmlFor="topic">Topic</Label>
                                        <Input
                                            id="topic"
                                            placeholder="e.g., Photosynthesis"
                                            value={topic}
                                            onChange={(e) => setTopic(e.target.value)}
                                            required
                                        />
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="subject">Subject</Label>
                                        <Input
                                            id="subject"
                                            placeholder="e.g., Biology"
                                            value={subject}
                                            onChange={(e) => setSubject(e.target.value)}
                                            required
                                        />
                                    </div>
                                </div>
                                <Button type="submit" disabled={isLoading || !topic.trim() || !subject.trim()} className="w-full">
                                    <Wand2 className="mr-2 h-4 w-4" />
                                    {isLoading ? 'Generating...' : 'Generate Guide'}
                                </Button>
                            </form>

                            {(isLoading || guide || error) && (
                                <div className="mt-6 border-t pt-6">
                                    {isLoading && <p className="text-center text-muted-foreground">The AI is generating your study guide...</p>}
                                    {error && <p className="text-center text-destructive">{error}</p>}
                                    {guide && (
                                        <Card>
                                            <CardHeader className="flex flex-row items-center gap-3">
                                                <Lightbulb className="h-6 w-6 text-primary" />
                                                <CardTitle>Your AI-Generated Study Guide for "{topic}"</CardTitle>
                                            </CardHeader>
                                            <CardContent>
                                                <div
                                                    className="prose prose-sm dark:prose-invert max-w-none"
                                                    dangerouslySetInnerHTML={{ __html: guide }}
                                                />
                                            </CardContent>
                                        </Card>
                                    )}
                                </div>
                            )}
                        </CardContent>
                    </Card>
                </div>
            </main>
        </div>
    );
}
